CREATE TABLE IF NOT EXISTS ingredients (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(100) NOT NULL,
    days_left INT NOT NULL CHECK (days_left >= 0),
    quantity VARCHAR(50) NOT NULL,
    storage_method VARCHAR(20)
    );